### ISSUE TITLE
Build path problems

### ISSUE THREAD

**Issue by WurstCommander** [brahalla/PhotoAlbum-api#1]
Hi!

I tried checkout your project.
I get the following problem:

> Build path entry is missing: PhotoAlbum-api-develop/src/test/java

and
com.brahalla.PhotoAlbum.controller.advice.GlobalExceptionHandlerController

has the wrong package name:

> package gov.tn.portal.vserv.controller.advice;

**Comment by ghost** [comment]
I've fixed the package name, but I don't get the build path error. What OS and java version are you using, and are you building with maven?

**Comment by WurstCommander** [comment]
Maven 3.1.1 and JDK7.

I get several build errors in com.brahalla.PhotoAlbum.controller.advice.GlobalExceptionHandlerController but I will try it again at home. Maybe I have problems with the proxy settings on this machine right now.

**Comment by ghost** [comment]
I'd like to see the full list of build errors.

**Comment by WurstCommander** [comment]
Hi,

all-clear signal from me, there seems to be a problem with my work proxy and the spring repos.
Everything works now!
